[package]
name = "mc_core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = {workspace = true}
attohttpc = {workspace = true}
log = {workspace = true}
md5 = {workspace = true}
toml = {workspace = true}
serde = {workspace = true}